= Dateibeschreibung

Bei der Bewirtschaftung eines Themas gibt es Attribute, deren Werte nicht frei erfasst, sondern aus einem vorgegebenen Katalog selektiert werden müssen (z.B. Gemeindenamen aus dem Katalog der Schwyzer Gemeinden). Die Gesamtheit der Kataloge eines Themas wird als Stammdaten bezeichnet. Sie werden in einer eigenen Datei gehalten (`+Stammdaten.xtf+`) und bilden eine Voraussetzung für die Datenerfassung.

Änderungen am Datenmodell und/oder Änderungen an den Stammdaten führen zu Anpassungen in der Datei `+Stammdaten.xtf+`. Die nachfolgende Tabelle zeigt, welche Stammdaten bei welchem Datenmodell zu verwenden sind.

[cols="30%, 20%, 40%, 10%",options="header"]
|===
| Modell +
(Version) | gültig ab | Beschreibung | Link
| SZ_Revitalisierungsplanung_Fliessgewaesser_V2 +
(2026-04-15)
| 2026-06-12
| Diese Datei enthält die Stammdaten mit den korrigierten GUIDs des Bundes.
| https://raw.githubusercontent.com/ch-sz-geo/A180/main/data/Stammdaten.xtf[*Datei*]
| SZ_Revitalisierungsplanung_Fliessgewaesser_V2 +
(2026-04-15)
| 2000-01-01
| Diese Datei enthält die erste Version der Stammdaten. Darin sind die GUIDs durch den Kanton vergeben, da jene im Bundesdatensatz nicht eindeutig sind.
| https://raw.githubusercontent.com/ch-sz-geo/A180/Bearbeitung/data/Stammdaten.xtf[*Datei*]
|===
