== Modelltransformationen
=== [todo] Transformation vom Bearbeitungsmodell ins Publikationsmodell
* Quellmodell: https://raw.githubusercontent.com/ch-sz-geo/A064/refs/heads/main/models/SZ_Schutzwald_V1_Bearbeitung.ili[Bearbeitungsmodell "SZ_Schutzwald_V1" (Version: 2025-01-23)]
* Zielmodell: https://raw.githubusercontent.com/ch-sz-geo/A064/refs/heads/main/models/SZ_Schutzwald_V1.ili[Publikationsmodell verwaltungsintern "SZ_Schutzwald_V1_Bearbeitung" (Version: 2025-01-23)]

=== Transformation ins minimale Geodatenmodell des Bundes
* Quellmodell: Das hier beschriebene Datenmodell
* Zielmodell: https://models.geo.admin.ch/BAFU/Revitalisierung_Fliessgewaesser_V1_2.ili[Revitalisierung_Fliessgewaesser_V1_2 (Version: 2024-06-13)]

==== Klasse `+AbschOekomorph+`
Die Daten zu dieser Klasse werden im Thema A026 geführt. Die Transformationsregel finden sich https://ch-sz-geo.github.io/A026/docs/modelldokumentation.html#_transformation_ins_minimale_geodatenmodell_des_bundes[hier].

==== Klasse `+Absturz+`
Die Daten zu dieser Klasse werden im Thema A026 geführt. Die Transformationsregel finden sich https://ch-sz-geo.github.io/A026/docs/modelldokumentation.html#_transformation_ins_minimale_geodatenmodell_des_bundes[hier].

==== Klasse `+Bauwerk+`
Die Daten zu dieser Klasse werden im Thema A026 geführt. Die Transformationsregel finden sich https://ch-sz-geo.github.io/A026/docs/modelldokumentation.html#_transformation_ins_minimale_geodatenmodell_des_bundes[hier].

==== Klasse `+AbschOEB+`
[cols=2*,options="header"]
|===
| Quellattribut | Zielattribut
|  Liniengeometrie, gebildet über die lineare Referenzierung auf der Grundlage von `+Achsgeometrie+` sowie `+LinearpositionVon+` und `+LinearpositionBis+` | `+Abschnitt+`
| Wert von `+Bewertung.OID+` +
hergeleitet über `+Bewertung__Abschnittsbewertung.rBewertung+` | `+OEB+`
| `+Bemerkung+` | `+Bemerkung+`
|===

==== Klasse `+AbschNutzen+`
[cols=2*,options="header"]
|===
| Quellattribut | Zielattribut
|  Liniengeometrie, gebildet über die lineare Referenzierung auf der Grundlage von `+Achsgeometrie+` sowie `+LinearpositionVon+` und `+LinearpositionBis+` | `+Abschnitt+`
| Wert von `+Nutzen.OID+` +
hergeleitet über `+Nutzen__Abschnittsnutzen.rNutzen+` | `+Nutzen+`
| `+Bemerkung+` | `+Bemerkung+`
|===

==== Klasse `+AbschPrio+`
[cols=2*,options="header"]
|===
| Quellattribut | Zielattribut
|  Liniengeometrie, gebildet über die lineare Referenzierung auf der Grundlage von `+Achsgeometrie+` sowie `+LinearpositionVon+` und `+LinearpositionBis+` | `+Abschnitt+`
| `+Frist+` | `+Frist+`
| Wert von `+Massnahme.OID+` +
hergeleitet über `+Massnahme__Abschnittsprioritaet.rMassnahme+` | `+Massnahmen+`
| `+Bemerkung+` | `+Bemerkung+`
|===

==== Klasse `+AbsturzNutzen+`
Die Daten zu dieser Klasse werden im Thema A026 geführt. Die Transformationsregel finden sich https://github.com/ch-sz-geo/A026/blob/main/docs/modelldokumentation/transformation.adoc#transformation-ins-minimale-geodatenmodell-des-bundes[hier].

=== [todo] Transformation ins WebGIS
* Quellmodell: Das hier beschriebene Datenmodell
* Zielmodell: keines (siehe unten)

==== Allgemeines
Für die WebGIS-Publikation werden die Daten optimiert. Dies ist häufig mit einer Denormalisierung verbunden ("flachwalzen" der Daten). Der Attributumfang richtet sich nach den Anforderungen der zuständigen Stelle und ist im Normalfall geringer als im Ausgangsmodell. Eine weitere Besonderheit kommt den Tabellen der WebGIS-Datenbank zu. Sie weisen Standard-Spalten auf, welche nicht Teil des Datenmodells sind. Es handelt sich um folgende Spalten:

**Standardspalten:**
[cols=2*,options="header"]
|===
| Spaltenname | Beschreibung
m| id | eindeutige Identifikation des Objektes; kann von der OID der Ausgangsdaten abweichen, falls Objekte zum Zweck der Publikation aufgeteilt werden müssen
m| etl_dt | Zeitstempel, an dem der Datensatz in die Tabelle geschrieben wurde (etl: extract - transfer - load)
m| etl_job | Name des Jobs, mit dem die Daten auf die Tabelle geschrieben wurde
m| asof_dt | Datum, an dem am Datensatz die letzten Änderungen vorgenommen wurden. Dieser Wert wird in den Metadaten des Datensatzes nachgeführt.
|===

Das WebGIS bezieht die Daten direkt aus der Datenbank. Aus diesem Grund wird nachfolgend von "Tabelle" und "Spalte" anstelle von "Klasse" und "Attribut" gesprochen. Der Klassenname erscheint lediglich in der Überschrift.

ifdef::backend-pdf[]
<<<
endif::[]
