== Modelltransformationen
=== Transformation vo der Struktur der Datenerfassung ins kantonale Datenmodell
* Quellmodell: Als Input fĂĽr das "Quellmodell" dient eine Excel-Liste, in welcher der Auftragnehmer Attributerweiterungen vorschlĂ¤gt.
* Zielmodell: Das hier beschriebene Datenmodell

==== Klasse `+Bauwerksbewertung+`
Die Klasse `+Bauwerksbewertung+` fĂĽhrt die Attribute zur Bewertung eines Bauwerks.
[cols=2*,options="header"]
|===
| Quellattribut | Zielattribut
| `+OBJECTID+` | `+Identifikator_Quellsystem+`
| `+ID+` | `+Identifikator_Analysesystem+`
| `+bauwerk_kennung+` | `+Identifikator_Bauwerk+`
| `+typ+` | todo: kantonaler Katalog erstellen
| `+SOHLENGEF+` | `+Sohlengefaelle+`
| `+HVI_PRO_HINDERNISGRUPPE+` | `+Habitatsvergroesserungsindex+`
| `+IDs_HINDERNISGRUPPE+` | ĂĽber `+rGruppe+` der Klasse `+Bauwerk+`
| `+FELDARBEIT+` | `+hatFeldbegehung+`
| `+AUFWAND_KL+` | `+rBauaufwand+`
| `+POTENZIAL_KL+` | `+rPotenzial+`
| `+PRAEFERENZ+` | `+rPraeferenz+`
| `+LOWHANGING_FRUIT+` | `+istNutzenoptimiert+`
| `+BemFeldAuf+` | `+Bemerkung_Feldaufnahme+`
| `+BemFeldRel+` | `+Bemerkung_Feldrelevanz+`
| `+BemNutzen+` | `+Bemerkung_Nutzen+`
| `+NutzenGIS+` | `+rGISNutzen+`
| `+Nutzen+` | `+rGISNutzen+` +
Die Werte von `+NutzenGIS+` und `+Nutzen+` sind identisch. Aus diesem Grund wird auf den gleichen Katalog verwiesen.
| `+Begruend+` | `+Begruendung+`
| `+BemPlau+` | `+Bemerkung_Plausibilisierung+`
| `+Massnahme+` | `+Massnahme+`
| `+PrioritĂ¤t+` | `+Prioritaet+`
|===

==== Klasse `+Bauwerk+`
Die Klasse `+Bauwerk+` dient dazu, eine Hindernisgruppe zu bilden. Im Quellsystem sind die Bauwerks-Kennungen als Komma-separierte Liste gefĂĽhrt. Diese werden auf dieser Klasse einzeln eingetragen und ĂĽber eine Beziehung der Klasse `+Bauwerksbewertung+` zugeordnet.
[cols=2*,options="header"]
|===
| Quellattribut | Zielattribut
| `+IDs_HINDERNISGRUPPE+` | `+Identifikator_Bauwerk+`
|===

==== Klasse `+Absturzbewertung+`
Die Klasse `+Absturzbewertung+` fĂĽhrt die Attribute zur Bewertung eines Absturzes.
[cols=2*,options="header"]
|===
| Quellattribut | Zielattribut
| `+OBJECTID+` | `+Identifikator_Quellsystem+`
| `+ID+` | `+Identifikator_Analysesystem+`
| `+bauwerk_kennung+` | `+Identifikator_Absturz+`
| `+typ+` | todo: kantonaler Katalog erstellen
| `+SOHLENGEF+` | `+Sohlengefaelle+`
| `+HVI_PRO_HINDERNISGRUPPE+` | `+Habitatsvergroesserungsindex+`
| `+IDs_HINDERNISGRUPPE+` | ĂĽber `+rGruppe+` der Klasse `+Absturz+`
| `+FELDARBEIT+` | `+hatFeldbegehung+`
| `+AUFWAND_KL+` | `+rBauaufwand+`
| `+POTENZIAL_KL+` | `+rPotenzial+`
| `+PRAEFERENZ+` | `+rPraeferenz+`
| `+LOWHANGING_FRUIT+` | `+istNutzenoptimiert+`
| `+BemFeldAuf+` | `+Bemerkung_Feldaufnahme+`
| `+BemFeldRel+` | `+Bemerkung_Feldrelevanz+`
| `+BemNutzen+` | `+Bemerkung_Nutzen+`
| `+NutzenGIS+` | `+rGISNutzen+`
| `+Nutzen+` | `+rGISNutzen+` +
Die Werte von `+NutzenGIS+` und `+Nutzen+` sind identisch. Aus diesem Grund wird auf den gleichen Katalog verwiesen.
| `+Begruend+` | `+Begruendung+`
| `+BemPlau+` | `+Bemerkung_Plausibilisierung+`
| `+Massnahme+` | `+Massnahme+`
| `+PrioritĂ¤t+` | `+Prioritaet+`
|===

==== Klasse `+Absturz+`
Die Klasse `+Absturz+` dient dazu, eine Hindernisgruppe zu bilden. Im Quellsystem sind die Absturz-Kennungen als Komma-separierte Liste gefĂĽhrt. Diese werden auf dieser Klasse einzeln eingetragen und ĂĽber eine Beziehung der Klasse `+Absturzbewertung+` zugeordnet.
[cols=2*,options="header"]
|===
| Quellattribut | Zielattribut
| `+IDs_HINDERNISGRUPPE+` | `+Identifikator_Absturz+`
|===

=== Transformation ins minimale Geodatenmodell des Bundes
* Quellmodell: Das hier beschriebene Datenmodell
* Zielmodell: https://models.geo.admin.ch/BAFU/Revitalisierung_Fliessgewaesser_V1_2.ili[Revitalisierung_Fliessgewaesser_V1_2 (Version: 2024-06-13)]

==== Klasse `+AbschOekomorph+`
Die Daten zu dieser Klasse werden im Thema A026 gefĂĽhrt. Die Transformationsregel finden sich https://ch-sz-geo.github.io/A026/docs/modelldokumentation.html#_transformation_ins_minimale_geodatenmodell_des_bundes[hier].

==== Klasse `+Absturz+`
Die Daten zu dieser Klasse werden im Thema A026 gefĂĽhrt. Die Transformationsregel finden sich https://ch-sz-geo.github.io/A026/docs/modelldokumentation.html#_transformation_ins_minimale_geodatenmodell_des_bundes[hier].

==== Klasse `+Bauwerk+`
Die Daten zu dieser Klasse werden im Thema A026 gefĂĽhrt. Die Transformationsregel finden sich https://ch-sz-geo.github.io/A026/docs/modelldokumentation.html#_transformation_ins_minimale_geodatenmodell_des_bundes[hier].

==== Klasse `+AbschOEB+`
[cols=2*,options="header"]
|===
| Quellattribut | Zielattribut
|  Liniengeometrie, gebildet ĂĽber die lineare Referenzierung auf der Grundlage von `+Achsgeometrie+` sowie `+LinearpositionVon+` und `+LinearpositionBis+` | `+Abschnitt+`
| Wert von `+Bewertung.OID+` +
hergeleitet ĂĽber `+Bewertung__Abschnittsbewertung.rBewertung+` | `+OEB+`
| `+Bemerkung+` | `+Bemerkung+`
|===

==== Klasse `+AbschNutzen+`
[cols=2*,options="header"]
|===
| Quellattribut | Zielattribut
|  Liniengeometrie, gebildet ĂĽber die lineare Referenzierung auf der Grundlage von `+Achsgeometrie+` sowie `+LinearpositionVon+` und `+LinearpositionBis+` | `+Abschnitt+`
| Wert von `+Nutzen.OID+` +
hergeleitet ĂĽber `+Nutzen__Abschnittsnutzen.rNutzen+` | `+Nutzen+`
| `+Bemerkung+` | `+Bemerkung+`
|===

==== Klasse `+AbschPrio+`
[cols=2*,options="header"]
|===
| Quellattribut | Zielattribut
|  Liniengeometrie, gebildet ĂĽber die lineare Referenzierung auf der Grundlage von `+Achsgeometrie+` sowie `+LinearpositionVon+` und `+LinearpositionBis+` | `+Abschnitt+`
| `+Frist+` | `+Frist+`
| Wert von `+Massnahme.OID+` +
hergeleitet ĂĽber `+Massnahme__Abschnittsprioritaet.rMassnahme+` | `+Massnahmen+`
| `+Bemerkung+` | `+Bemerkung+`
|===

==== Klasse `+AbsturzNutzen+`
Die Daten zu dieser Klasse werden im Thema A026 gefĂĽhrt. Die Transformationsregel finden sich https://github.com/ch-sz-geo/A026/blob/main/docs/modelldokumentation/transformation.adoc#transformation-ins-minimale-geodatenmodell-des-bundes[hier].

=== [todo] Transformation ins WebGIS
* Quellmodell: Das hier beschriebene Datenmodell
* Zielmodell: keines (siehe unten)

==== Allgemeines
FĂĽr die WebGIS-Publikation werden die Daten optimiert. Dies ist hĂ¤ufig mit einer Denormalisierung verbunden ("flachwalzen" der Daten). Der Attributumfang richtet sich nach den Anforderungen der zustĂ¤ndigen Stelle und ist im Normalfall geringer als im Ausgangsmodell. Eine weitere Besonderheit kommt den Tabellen der WebGIS-Datenbank zu. Sie weisen Standard-Spalten auf, welche nicht Teil des Datenmodells sind. Es handelt sich um folgende Spalten:

**Standardspalten:**
[cols=2*,options="header"]
|===
| Spaltenname | Beschreibung
m| id | eindeutige Identifikation des Objektes; kann von der OID der Ausgangsdaten abweichen, falls Objekte zum Zweck der Publikation aufgeteilt werden mĂĽssen
m| etl_dt | Zeitstempel, an dem der Datensatz in die Tabelle geschrieben wurde (etl: extract - transfer - load)
m| etl_job | Name des Jobs, mit dem die Daten auf die Tabelle geschrieben wurde
m| asof_dt | Datum, an dem am Datensatz die letzten Ă„nderungen vorgenommen wurden. Dieser Wert wird in den Metadaten des Datensatzes nachgefĂĽhrt.
|===

Das WebGIS bezieht die Daten direkt aus der Datenbank. Aus diesem Grund wird nachfolgend von "Tabelle" und "Spalte" anstelle von "Klasse" und "Attribut" gesprochen. Der Klassenname erscheint lediglich in der Ăśberschrift.

ifdef::backend-pdf[]
<<<
endif::[]
